name: autth_injustice_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.5.0
  dropdown_button2: ^2.3.9
  auto_injector: ^2.1.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  faker_dart: ^0.2.3
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  font_awesome_flutter: ^11.0.0
  go_router: ^17.2.2
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.5
  signals_flutter: ^6.3.0
  flutter_svg: ^2.0.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.14.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/